apiVersion: v1
kind: Service
metadata:
  name: automotive-laravel-service
  labels:
    app: automotive-laravel
spec:
  type: NodePort
  selector:
    app: automotive-laravel
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
